import fs from "fs";

const URL = "https://dummyjson.com/products?limit=0";

async function main() {
  const res = await fetch(URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch products: ${res.status}`);
  }

  const data = await res.json();
  const products = Array.isArray(data.products) ? data.products : [];

  const map = {};
  for (const p of products) {
    if (p && typeof p.id === "number") {
      map[p.id] = p.title || `Product #${p.id}`;
    }
  }

  const out = `// Auto-generated by scripts/generateProductMap.mjs
// Do not edit manually.
export const PRODUCT_MAP = ${JSON.stringify(map, null, 2)};
`;

  const target = "frontend/src/productMap.js";
  fs.mkdirSync("frontend/src", { recursive: true });
  fs.writeFileSync(target, out, "utf8");

  console.log(
    "Wrote",
    target,
    "with",
    Object.keys(map).length,
    "products"
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
